function MarkerManager(a,c){var b=this;b.map_=a;b.mapZoom_=a.getZoom();b.projectionHelper_=new ProjectionHelperOverlay(a);google.maps.event.addListener(b.projectionHelper_,"ready",function(){b.projection_=this.getProjection();b.initialize(a,c)})}
MarkerManager.prototype.initialize=function(a,c){var b=this,c=c||{};b.tileSize_=MarkerManager.DEFAULT_TILE_SIZE_;var d=a.mapTypes,e=1,g;for(g in d)if(typeof a.mapTypes.get(g)==="object"&&typeof a.mapTypes.get(g).maxZoom==="number"){var h=a.mapTypes.get(g).maxZoom;h>e&&(e=h)}b.maxZoom_=c.maxZoom||19;b.trackMarkers_=c.trackMarkers;b.show_=c.show||!0;d=typeof c.borderPadding==="number"?c.borderPadding:MarkerManager.DEFAULT_BORDER_PADDING_;b.swPadding_=new google.maps.Size(-d,d);b.nePadding_=new google.maps.Size(d,
-d);b.borderPadding_=d;b.gridWidth_={};b.grid_={};b.grid_[b.maxZoom_]={};b.numMarkers_={};b.numMarkers_[b.maxZoom_]=0;google.maps.event.addListener(a,"dragend",function(){b.onMapMoveEnd_()});google.maps.event.addListener(a,"zoom_changed",function(){b.onMapMoveEnd_()});b.removeOverlay_=function(a){a.setMap(null);b.shownMarkers_--};b.addOverlay_=function(a){b.show_&&(a.setMap(b.map_),b.shownMarkers_++)};b.resetManager_();b.shownMarkers_=0;b.shownBounds_=b.getMapGridBounds_();google.maps.event.trigger(b,
"loaded")};MarkerManager.DEFAULT_TILE_SIZE_=1024;MarkerManager.DEFAULT_BORDER_PADDING_=100;MarkerManager.MERCATOR_ZOOM_LEVEL_ZERO_RANGE=256;MarkerManager.prototype.resetManager_=function(){for(var a=MarkerManager.MERCATOR_ZOOM_LEVEL_ZERO_RANGE,c=0;c<=this.maxZoom_;++c)this.grid_[c]={},this.numMarkers_[c]=0,this.gridWidth_[c]=Math.ceil(a/this.tileSize_),a<<=1};MarkerManager.prototype.clearMarkers=function(){this.processAll_(this.shownBounds_,this.removeOverlay_);this.resetManager_()};
MarkerManager.prototype.getTilePoint_=function(a,c,b){a=this.projectionHelper_.LatLngToPixel(a,c);return new google.maps.Point(Math.floor((a.x+b.width)/this.tileSize_),Math.floor((a.y+b.height)/this.tileSize_))};
MarkerManager.prototype.addMarkerBatch_=function(a,c,b){var d=this,e=a.getPosition();a.MarkerManager_minZoom=c;this.trackMarkers_&&google.maps.event.addListener(a,"changed",function(a,b,c){d.onMarkerMoved_(a,b,c)});for(e=this.getTilePoint_(e,b,new google.maps.Size(0,0,0,0));b>=c;b--)this.getGridCellCreate_(e.x,e.y,b).push(a),e.x>>=1,e.y>>=1};
MarkerManager.prototype.isGridPointVisible_=function(a){var c=this.shownBounds_.minY<=a.y&&a.y<=this.shownBounds_.maxY,b=this.shownBounds_.minX,d=b<=a.x&&a.x<=this.shownBounds_.maxX;!d&&b<0&&(d=this.gridWidth_[this.shownBounds_.z],d=b+d<=a.x&&a.x<=d-1);return c&&d};MarkerManager.prototype.onMarkerMoved_=function(a,c,b){for(var d=this.maxZoom_,e=!1,c=this.getTilePoint_(c,d,new google.maps.Size(0,0,0,0)),b=this.getTilePoint_(b,d,new google.maps.Size(0,0,0,0));d>=0&&(c.x!==b.x||c.y!==b.y);){var g=this.getGridCellNoCreate_(c.x,c.y,d);g&&this.removeFromArray_(g,a)&&this.getGridCellCreate_(b.x,b.y,d).push(a);d===this.mapZoom_&&(this.isGridPointVisible_(c)?this.isGridPointVisible_(b)||(this.removeOverlay_(a),e=!0):this.isGridPointVisible_(b)&&(this.addOverlay_(a),
e=!0));c.x>>=1;c.y>>=1;b.x>>=1;b.y>>=1;--d}e&&this.notifyListeners_()};MarkerManager.prototype.removeMarker=function(a){for(var c=this.maxZoom_,b=!1,d=this.getTilePoint_(a.getPosition(),c,new google.maps.Size(0,0,0,0));c>=0;){var e=this.getGridCellNoCreate_(d.x,d.y,c);e&&this.removeFromArray_(e,a);c===this.mapZoom_&&this.isGridPointVisible_(d)&&(this.removeOverlay_(a),b=!0);d.x>>=1;d.y>>=1;--c}b&&this.notifyListeners_();this.numMarkers_[a.MarkerManager_minZoom]--};
MarkerManager.prototype.addMarkers=function(a,c,b){for(var b=this.getOptMaxZoom_(b),d=a.length-1;d>=0;d--)this.addMarkerBatch_(a[d],c,b);this.numMarkers_[c]+=a.length};MarkerManager.prototype.getOptMaxZoom_=function(a){return a||this.maxZoom_};MarkerManager.prototype.getMarkerCount=function(a){for(var c=0,b=0;b<=a;b++)c+=this.numMarkers_[b];return c};
MarkerManager.prototype.getMarker=function(a,c,b){var d=new google.maps.LatLng(a,c),e=this.getTilePoint_(d,b,new google.maps.Size(0,0,0,0)),d=new google.maps.Marker({position:d}),b=this.getGridCellNoCreate_(e.x,e.y,b);if(b!==void 0)for(e=0;e<b.length;e++)a===b[e].getLatLng().lat()&&c===b[e].getLatLng().lng()&&(d=b[e]);return d};
MarkerManager.prototype.addMarker=function(a,c,b){b=this.getOptMaxZoom_(b);this.addMarkerBatch_(a,c,b);this.isGridPointVisible_(this.getTilePoint_(a.getPosition(),this.mapZoom_,new google.maps.Size(0,0,0,0)))&&c<=this.shownBounds_.z&&this.shownBounds_.z<=b&&(this.addOverlay_(a),this.notifyListeners_());this.numMarkers_[c]++};function GridBounds(a){this.minX=Math.min(a[0].x,a[1].x);this.maxX=Math.max(a[0].x,a[1].x);this.minY=Math.min(a[0].y,a[1].y);this.maxY=Math.max(a[0].y,a[1].y)}
GridBounds.prototype.equals=function(a){return this.maxX===a.maxX&&this.maxY===a.maxY&&this.minX===a.minX&&this.minY===a.minY?!0:!1};GridBounds.prototype.containsPoint=function(a){return this.minX<=a.x&&this.maxX>=a.x&&this.minY<=a.y&&this.maxY>=a.y};MarkerManager.prototype.getGridCellCreate_=function(a,c,b){var d=this.grid_[b];a<0&&(a+=this.gridWidth_[b]);b=d[a];if(!b)return b=d[a]=[],b[c]=[];a=b[c];if(!a)return b[c]=[];return a};
MarkerManager.prototype.getGridCellNoCreate_=function(a,c,b){var d=this.grid_[b];a<0&&(a+=this.gridWidth_[b]);return(a=d[a])?a[c]:void 0};MarkerManager.prototype.getGridBounds_=function(a,c,b,d){var c=Math.min(c,this.maxZoom_),e=a.getSouthWest(),a=a.getNorthEast(),b=this.getTilePoint_(e,c,b),d=this.getTilePoint_(a,c,d),g=this.gridWidth_[c];if(a.lng()<e.lng()||d.x<b.x)b.x-=g;if(d.x-b.x+1>=g)b.x=0,d.x=g-1;e=new GridBounds([b,d]);e.z=c;return e};
MarkerManager.prototype.getMapGridBounds_=function(){return this.getGridBounds_(this.map_.getBounds(),this.mapZoom_,this.swPadding_,this.nePadding_)};MarkerManager.prototype.onMapMoveEnd_=function(){this.objectSetTimeout_(this,this.updateMarkers_,0)};MarkerManager.prototype.objectSetTimeout_=function(a,c,b){return window.setTimeout(function(){c.call(a)},b)};MarkerManager.prototype.visible=function(){return this.show_?!0:!1};MarkerManager.prototype.isHidden=function(){return!this.show_};
MarkerManager.prototype.show=function(){this.show_=!0;this.refresh()};MarkerManager.prototype.hide=function(){this.show_=!1;this.refresh()};MarkerManager.prototype.toggle=function(){this.show_=!this.show_;this.refresh()};MarkerManager.prototype.refresh=function(){this.shownMarkers_>0&&this.processAll_(this.shownBounds_,this.removeOverlay_);this.show_&&this.processAll_(this.shownBounds_,this.addOverlay_);this.notifyListeners_()};
MarkerManager.prototype.updateMarkers_=function(){this.mapZoom_=this.map_.getZoom();var a=this.getMapGridBounds_();if(!(a.equals(this.shownBounds_)&&a.z===this.shownBounds_.z))a.z!==this.shownBounds_.z?(this.processAll_(this.shownBounds_,this.removeOverlay_),this.show_&&this.processAll_(a,this.addOverlay_)):(this.rectangleDiff_(this.shownBounds_,a,this.removeCellMarkers_),this.show_&&this.rectangleDiff_(a,this.shownBounds_,this.addCellMarkers_)),this.shownBounds_=a,this.notifyListeners_()};
MarkerManager.prototype.notifyListeners_=function(){google.maps.event.trigger(this,"changed",this.shownBounds_,this.shownMarkers_)};MarkerManager.prototype.processAll_=function(a,c){for(var b=a.minX;b<=a.maxX;b++)for(var d=a.minY;d<=a.maxY;d++)this.processCellMarkers_(b,d,a.z,c)};MarkerManager.prototype.processCellMarkers_=function(a,c,b,d){if(a=this.getGridCellNoCreate_(a,c,b))for(c=a.length-1;c>=0;c--)d(a[c])};
MarkerManager.prototype.removeCellMarkers_=function(a,c,b){this.processCellMarkers_(a,c,b,this.removeOverlay_)};MarkerManager.prototype.addCellMarkers_=function(a,c,b){this.processCellMarkers_(a,c,b,this.addOverlay_)};MarkerManager.prototype.rectangleDiff_=function(a,c,b){var d=this;d.rectangleDiffCoords_(a,c,function(c,g){b.apply(d,[c,g,a.z])})};
MarkerManager.prototype.rectangleDiffCoords_=function(a,c,b){var d=a.minX,e=a.minY,g=a.maxX,a=a.maxY,h=c.minX,i=c.minY,k=c.maxX,c=c.maxY,f,j;for(f=d;f<=g;f++){for(j=e;j<=a&&j<i;j++)b(f,j);for(j=Math.max(c+1,e);j<=a;j++)b(f,j)}for(j=Math.max(e,i);j<=Math.min(a,c);j++){for(f=Math.min(g+1,h)-1;f>=d;f--)b(f,j);for(f=Math.max(d,k+1);f<=g;f++)b(f,j)}};MarkerManager.prototype.removeFromArray_=function(a,c,b){for(var d=0,e=0;e<a.length;++e)if(a[e]===c||b&&a[e]===c)a.splice(e--,1),d++;return d};
function ProjectionHelperOverlay(a){this.setMap(a);this._map=a;this._X0=this._Y0=this._X1=this._Y1=this._zoom=-1}ProjectionHelperOverlay.prototype=new google.maps.OverlayView;ProjectionHelperOverlay.prototype.LngToX_=function(a){return 1+a/180};ProjectionHelperOverlay.prototype.LatToY_=function(a){a=Math.sin(a*Math.PI/180);return 1-0.5/Math.PI*Math.log((1+a)/(1-a))};
ProjectionHelperOverlay.prototype.LatLngToPixel=function(a,c){this.getProjection().fromLatLngToDivPixel(a);return{x:~~(0.5+this.LngToX_(a.lng())*(2<<c+6)),y:~~(0.5+this.LatToY_(a.lat())*(2<<c+6))}};ProjectionHelperOverlay.prototype.draw=function(){if(!this.ready)this.ready=!0,google.maps.event.trigger(this,"ready")};var StyledIconTypes={},StyledMarker,StyledIcon;
(function(){var a=google.maps,c=a.Point,b=a.event,d=a.MarkerImage;StyledMarker=function(a){var b=this.styleIcon=a.styleIcon;this.bindTo("icon",b);this.bindTo("shadow",b);this.bindTo("shape",b);this.setOptions(a)};StyledMarker.prototype=new a.Marker;StyledIcon=function(a,c,h){function i(){var c=document.createElement("img"),g=document.createElement("img");b.addDomListenerOnce(g,"load",function(){var c=g.width,b=g.height;f.set(l,new d(a.getShadowURL(f),null,null,a.getShadowAnchor(f,c,b)));simage=null});
b.addDomListenerOnce(c,"load",function(){var b=c.width,g=c.height;f.set(j,new d(a.getURL(f),null,null,a.getAnchor(f,b,g)));f.set(n,a.getShape(f,b,g));c=null});c.src=a.getURL(f);g.src=a.getShadowURL(f)}var k,f=this,j="icon",l="shadow",n="shape",m=[];f.as_=function(a){m.push(a);for(k in c)a.set(k,c[k])};if(a!==StyledIconTypes.CLASS){for(k in a.defaults)f.set(k,a.defaults[k]);f.setValues(c);f.set(j,a.getURL(f));f.set(l,a.getShadowURL(f));h&&h.as_(f);i();f.changed=function(a){a!==j&&a!==n&&a!==l&&i()}}else f.setValues(c),
f.changed=function(a){c[a]=f.get(a);for(k=0;k<m.length;k++)m[k].set(a,f.get(a))},h&&h.as_(f)};StyledIcon.prototype=new a.MVCObject;StyledIconTypes.CLASS={};StyledIconTypes.MARKER={defaults:{text:"",color:"00ff00",fore:"000000",starcolor:null},getURL:function(a){var c=a.get("starcolor"),b=a.get("text"),d=a.get("color").replace(/#/,""),k=a.get("fore").replace(/#/,""),a=c?"http://chart.apis.google.com/chart?chst=d_map_xpin_letter&chld=pin_star|":"http://chart.apis.google.com/chart?chst=d_map_pin_letter&chld=";
b&&(b=b.substr(0,2));a+=b+"|";a+=d+"|";a+=k;c&&(a+="|"+c.replace(/#/,""));return a},getShadowURL:function(a){return a.get("starcolor")?"http://chart.apis.google.com/chart?chst=d_map_xpin_shadow&chld=pin_star":"http://chart.apis.google.com/chart?chst=d_map_pin_shadow"},getAnchor:function(a,b,d){return new c(b/2,d)},getShadowAnchor:function(a,b,d){return new c(b/4,d)},getShape:function(a,b,c){a={};a.coord=[b/2,c,0.4375*b,0.625*c,0.3125*b,0.4375*c,0.21875*b,0.3125*c,0.3125*b,0.125*c,0.5*b,0,0.6875*b,
0.125*c,0.78125*b,0.3125*c,0.6875*b,0.4375*c,0.5625*b,0.625*c];for(b=0;b<a.coord.length;b++)a.coord[b]=Math.round(a.coord[b]);a.type="poly";return a}};StyledIconTypes.BUBBLE={defaults:{text:"",color:"00ff00",fore:"000000"},getURL:function(a){var b="http://chart.apis.google.com/chart?chst=d_bubble_text_small&chld=bb|";b+=a.get("text")+"|";b+=a.get("color").replace(/#/,"")+"|";b+=a.get("fore").replace(/#/,"");return b},getShadowURL:function(a){return"http://chart.apis.google.com/chart?chst=d_bubble_text_small_shadow&chld=bb|"+
a.get("text")},getAnchor:function(){return new google.maps.Point(0,42)},getShadowAnchor:function(){return new google.maps.Point(0,44)},getShape:function(a,b){var c={};c.coord=[0,44,13,26,13,6,17,1,b-4,1,b,6,b,21,b-4,26,21,26];c.type="poly";return c}}})();(function(a){a.extend({metadata:{defaults:{type:"class",name:"metadata",cre:/({.*})/,single:"metadata"},setType:function(a,b){this.defaults.type=a;this.defaults.name=b},get:function(c,b){var d=a.extend({},this.defaults,b);if(!d.single.length)d.single="metadata";var e=a.data(c,d.single);if(e)return e;var e="{}",g=function(a){if(typeof a!="string")return a;return a=eval("("+a+")")};if(d.type=="html5"){var h={};a(c.attributes).each(function(){var a=this.nodeName;if(a.match(/^data-/))a=a.replace(/^data-/,
"");else return!0;h[a]=g(this.nodeValue)})}else{if(d.type=="class"){var i=d.cre.exec(c.className);i&&(e=i[1])}else if(d.type=="elem"){if(!c.getElementsByTagName)return;i=c.getElementsByTagName(d.name);i.length&&(e=a.trim(i[0].innerHTML))}else c.getAttribute!=void 0&&(i=c.getAttribute(d.name))&&(e=i);h=g(e.indexOf("{")<0?"{"+e+"}":e)}a.data(c,d.single,h);return h}}});a.fn.metadata=function(c){return a.metadata.get(this[0],c)}})(jQuery);(function(a){a.jMapping=function(c,b){var d,e,g,h,i,k,f,j,c=typeof c=="string"?a(c).get(0):c;if(a(c).data("jMapping"))return a(c).data("jMapping");else{d=a.extend(!0,{},a.jMapping.defaults);a.extend(!0,d,b);e={};j=[];var l=function(b){var g;g=[d.side_bar_selector,d.location_selector,d.info_window_selector].join(" ");a(g).hide();k=n();f=o(b);b?(e={},j=[],i.clearMarkers(),google.maps.event.trigger(h,"resize"),h.fitBounds(f),d.force_zoom_level&&h.setZoom(d.force_zoom_level)):(h=d.map_config?new google.maps.Map(c,
d.map_config):new google.maps.Map(c,{navigationControlOptions:{style:google.maps.NavigationControlStyle.SMALL},mapTypeControl:!1,mapTypeId:google.maps.MapTypeId.ROADMAP,zoom:13}),h.fitBounds(f),d.force_zoom_level&&h.setZoom(d.force_zoom_level),i=new MarkerManager(h));k.each(function(){var b=r(this);if(d.link_selector!==!1){var c=a(this),e=c.metadata(d.metadata_options);c.find(d.link_selector).attr("href","#"+e.id)}a(document).trigger("markerCreated.jMapping",[b])});b?p():google.maps.event.addListener(i,
"loaded",function(){p();d.default_zoom_level&&h.setZoom(d.default_zoom_level)});d.link_selector!==!1&&!b&&s()},n=function(){return a(d.side_bar_selector+" "+d.location_selector)},m=function(b){return k.map(function(){b&&a(this).data("metadata",!1);return a(this).metadata(d.metadata_options)})},o=function(b){var b=m(b),c;c=b.length?a.jMapping.makeGLatLng(b[0].point):a.jMapping.makeGLatLng(d.default_point);c=new google.maps.LatLngBounds(c,c);for(var e=1,f=b.length;e<f;e++)c.extend(a.jMapping.makeGLatLng(b[e].point));
return c},r=function(b){var c=a(b),f,g,i,b=c.metadata(d.metadata_options);f=a.jMapping.makeGLatLng(b.point);d.category_icon_options?(icon_options=d.category_icon_options?a.isFunction(d.category_icon_options)?d.category_icon_options(b.category):d.category_icon_options[b.category]||d.category_icon_options["default"]:{},g=typeof icon_options==="string"||icon_options instanceof google.maps.MarkerImage?new google.maps.Marker({icon:icon_options,position:f,map:h}):new StyledMarker({styleIcon:new StyledIcon(StyledIconTypes.MARKER,
icon_options),position:f,map:h})):g=new google.maps.Marker({position:f,map:h});c=c.find(d.info_window_selector);c.length>0&&(i=new google.maps.InfoWindow({content:c.html(),maxWidth:d.info_window_max_width}),j.push(i),google.maps.event.addListener(g,"click",function(){a.each(j,function(a,b){i!=b&&b.close()});i.open(h,g)}));return e[parseInt(b.id,10)]=g},p=function(){d.always_show_markers===!0?min_zoom=0:(zoom_level=h.getZoom(),min_zoom=zoom_level<7?0:zoom_level-7);i.addMarkers(q(),min_zoom);i.refresh();
d.force_zoom_level&&h.setZoom(d.force_zoom_level)},s=function(){var b=[d.side_bar_selector,d.location_selector,d.link_selector].join(" ");a(b).live("click",function(b){b.preventDefault();b=parseInt(a(this).attr("href").split("#")[1],10);google.maps.event.trigger(e[b],"click")})},q=function(){var b=[];a.each(e,function(a,c){b.push(c)});return b};a(document).trigger("beforeMapping.jMapping",[d])!=!1?(l(),g=!0):g=!1;g={gmarkers:e,settings:d,mapped:g,map:h,markerManager:i,gmarkersArray:q,getBounds:o,
getPlacesData:m,getPlaces:n,update:function(){if(a(document).trigger("beforeUpdate.jMapping",[this])!=!1)l(!0),this.map=h,this.gmarkers=e,this.markerManager=i,a(document).trigger("afterUpdate.jMapping",[this])}};a(document).trigger("afterMapping.jMapping",[g]);return g}};a.extend(a.jMapping,{defaults:{side_bar_selector:"#map-side-bar:first",location_selector:".map-location",link_selector:"a.map-link",info_window_selector:".info-box",info_window_max_width:425,default_point:{lat:0,lng:0},metadata_options:{type:"attr",
name:"data-jmapping"}},makeGLatLng:function(a){return new google.maps.LatLng(a.lat,a.lng)}});a.fn.jMapping=function(c){c=="update"&&a(this[0]).data("jMapping")?a(this[0]).data("jMapping").update():(c=="update"&&(c={}),a(this[0]).data("jMapping",a.jMapping(this[0],c)));return this}})(jQuery);